### PR TITLE
AccidentalMerge_Ticket43 "Eligible personnel page 18 branch"

### PR DESCRIPTION
**Pull request by PHampy**
Reverts yichenfeng/AAFApplicationAngular#43

### CODE REVIEW

**Comment by ryanturner** [comment]
@PHampy ,

Before I can move forward with the review, will you please resolve the conflicts? (they're listed above)

**Comment by katherinetucker** [comment]
resolved conflicts

**Comment by ryanturner** [comment]
@PHampy Hey Phil, I'm still confused by this. From what I see, this removes a ton of bower_component sources, makes an indent change to index.html, removes some css styling, removes the eligablePersonnel controller implementation, updates the eligible personnel template, and removes the heading from the incidentInfo page. The title of this is AccidentalMerge -- I don't know what that means. The pull request is to add an accidental merge?

Until there's explanation for what this PR represents, I can't adequately review it.

**Comment by ryanturner** [comment]
Closed because @PHampy migrated his work out of this repo into his fork, so the corrections wont occur here.

**Pull request closed without merging**
